### PR TITLE
Major sdk update

### PR DESCRIPTION
**Pull request by Arondondon**
Update includes the following:
1. Removing CLI dependencies. Now SDK does not depend on CLI in any way and works separately. In addition, as a result of this, the logic of some methods in SDK has changed, as well as the project structure - the client_lib_generator, utils, ipfs_utils, config and service_metadata modules have been added.
2. Documentation. Complete technical documentation has been written (project directory "docs"). The README.md file has also been updated, now it contains a complete description of all the functionality of the Python SDK.
3. Examples. There are two examples of using Python SDK to create custom applications. Among them, one is small - a calculator based on the SIngularityNET platform service, and the second is a full-fledged console application that uses all the functionality of the SDK. For both examples, .md files with tutorials on creating these examples are written. (Project directory "examples").

### CODE REVIEW

**Review by kiruxaspb — COMMENTED** [review]
Docs approved

**Review by kiruxaspb — COMMENTED** [review]
Approved update docs

**Review by kiruxaspb — APPROVED** [review]

**Review by kiruxaspb — CHANGES_REQUESTED** [review]
Update docs for config update

**Review by kiruxaspb — APPROVED** [review]

**Comment by kiruxaspb** [comment]
@Necr0x0Der Could your please review this one PR?

**Comment by Necr0x0Der** [comment]
> @Necr0x0Der Could your please review this one PR?
> 
> Here we have updated the moment and now private keys are not stored in idenitity.

Hmmm... The PR is quite large for a comprehensive review for me atm. What I see is that a lot of code was moved from cli to sdk, which is good. Config has become more compact and private keys are not stored, which are also good. This can be easily adopted in sdk in metta.
I'm not sure why there are so many proto files and pre-build pb2_grpc files in `resources`? Do they describe a standard API for daemons and are not stored on ipfs?
In any case, I don't see issues with changes on the client side from a quick glance.

**Comment by kiruxaspb** [comment]
> I'm not sure why there are so many proto files and pre-build pb2_grpc files in `resources`? Do they describe a standard API for daemons and are not stored on ipfs? In any case, I don't see issues with changes on the client side from a quick glance.

Thank you for review, @Necr0x0Der.

Yes, proto files stored in `resources` describe fixed API for daemons and `IPFS` downloads checks.
These are service protos, and I think it's more efficient to store them immediately in the package than to add additional downloading from `IPFS`, compiling and custom importing of these proto files in `snet.sdk` codebase.

We will add the [issue](https://github.com/singnet/snet-sdk-python/issues/66) of moving service protos to decentralized storage in our **backlog**.

**Comment by DaddyWesker** [comment]
> Initializes the m dict with empty of default values.
Probably there should be 'or' not 'of'. It is in https://github.com/Arondondon/snet-sdk-python/blob/development/docs/metadata_provider/service_metadata.md file

**Comment by Arondondon** [comment]
Thank you for review, @DaddyWesker.
You were right about the issues in [service_metadata.md](https://github.com/Arondondon/snet-sdk-python/blob/development/docs/metadata_provider/service_metadata.md) and [calculator.py](https://github.com/Arondondon/snet-sdk-python/blob/development/examples/calculator.py). Currently, they have been fixed.

**Review by kiruxaspb — APPROVED** [review]
Approved

**Pull request merged**
